BRAND_CATEGORIES = [
    ("Pet-Brands", "Pet-Brands", ""),
    ("Owner-Brands", "Owner-Brands", ""),
    ("Forced-Brands", "Forced-Brands", "Nur Owner können diese ihren Pets aufdrücken."),
    ("Shame-Brands", "Shame-Brands", "Für alle, die digitale Selbstachtung für überschätzt halten."),
    ("Legendary-Brands", "Legendary-Brands", ""),
]


DEFAULT_BRANDS = [
    ("Gekauftes Problem", "Pet-Brands", 500, "self"),
    ("Leinenpet", "Pet-Brands", 750, "self"),
    ("Property With Attitude", "Pet-Brands", 750, "self"),
    ("Good Pet, Bad Investment", "Pet-Brands", 1000, "self"),
    ("Too Expensive To Behave", "Pet-Brands", 1000, "self"),
    ("Luxus Auf Knien", "Pet-Brands", 1500, "self"),
    ("Owned And Annoying", "Pet-Brands", 1500, "self"),
    ("Teuer Und Hörig", "Pet-Brands", 1500, "self"),
    ("Collar Included", "Pet-Brands", 2000, "self"),
    ("Bought With Regret", "Pet-Brands", 2500, "self"),
    ("Master of Puppets", "Owner-Brands", 1000, "owner"),
    ("Leash Collector", "Owner-Brands", 1500, "owner"),
    ("Cold Handler", "Owner-Brands", 2000, "owner"),
    ("Paid Authority", "Owner-Brands", 2000, "owner"),
    ("No Ethics, Just Coins", "Owner-Brands", 2500, "owner"),
    ("Collar Capitalist", "Owner-Brands", 3000, "owner"),
    ("Buyer of Obedience", "Owner-Brands", 3000, "owner"),
    ("Boss With a Leash", "Owner-Brands", 4000, "owner"),
    ("Owner of Consequences", "Owner-Brands", 7500, "owner"),
    ("Black Leash Holder", "Owner-Brands", 10000, "owner"),
    ("Not My Choice", "Forced-Brands", 1000, "forced"),
    ("Owner Wanted This", "Forced-Brands", 1000, "forced"),
    ("Against My Will", "Forced-Brands", 1500, "forced"),
    ("Trag Ich Leider", "Forced-Brands", 1500, "forced"),
    ("Forced to Match", "Forced-Brands", 2000, "forced"),
    ("Paid Humiliation", "Forced-Brands", 2500, "forced"),
    ("Muss So Bleiben", "Forced-Brands", 2500, "forced"),
    ("Branded by Bad Taste", "Forced-Brands", 3000, "forced"),
    ("Wurde Nicht Gefragt", "Forced-Brands", 3000, "forced"),
    ("Sorry, My Owner Paid", "Forced-Brands", 3500, "forced"),
    ("Kein Refund", "Shame-Brands", 500, "shame"),
    ("Walking Receipt", "Shame-Brands", 750, "shame"),
    ("Würde Verkauft", "Shame-Brands", 750, "shame"),
    ("Public Mistake", "Shame-Brands", 1000, "shame"),
    ("Scham Deluxe", "Shame-Brands", 1500, "shame"),
    ("Bad Purchase Energy", "Shame-Brands", 1500, "shame"),
    ("Quittung Auf Beinen", "Shame-Brands", 1500, "shame"),
    ("Dignity Offline", "Shame-Brands", 2000, "shame"),
    ("Too Expensive For Pride", "Shame-Brands", 2500, "shame"),
    ("Admin Should Have Stopped This", "Shame-Brands", 3000, "shame"),
    ("Black Collar Asset", "Legendary-Brands", 5000, "legendary"),
    ("Command Locked", "Legendary-Brands", 5000, "legendary"),
    ("Privatbesitz", "Legendary-Brands", 6000, "legendary"),
    ("Owned in Public", "Legendary-Brands", 6000, "legendary"),
    ("Leash Protocol", "Legendary-Brands", 7000, "legendary"),
    ("Hart Gebrandet", "Legendary-Brands", 7500, "legendary"),
    ("Bound And Budgeted", "Legendary-Brands", 8000, "legendary"),
    ("Endstufe Besitz", "Legendary-Brands", 9000, "legendary"),
    ("Permanent Bad Decision", "Legendary-Brands", 10000, "legendary"),
    ("Deluxe Erniedrigt", "Legendary-Brands", 12000, "legendary"),
]


LEGACY_BRAND_RENAMES = [
    ("Coin-Owned Creature", "Gekauftes Problem"),
    ("Premium Property", "Leinenpet"),
    ("Leashed But Loud", "Property With Attitude"),
    ("Property With Attitude", "Good Pet, Bad Investment"),
    ("Bought, Not Broken", "Too Expensive To Behave"),
    ("Too Expensive To Own", "Luxus Auf Knien"),
    ("Dignity On Cooldown", "Owned And Annoying"),
    ("Pretty Little Problem", "Teuer Und Hörig"),
    ("Teuer Und Hoerig", "Teuer Und Hörig"),
    ("Leashed But Untamed", "Collar Included"),
    ("Owner's Worst Investment", "Bought With Regret"),
    ("Ownerâ€™s Worst Investment", "Bought With Regret"),
    ("The Leash Holder", "Master of Puppets"),
    ("Cold Command", "Leash Collector"),
    ("Owner With Consequences", "Cold Handler"),
    ("Certified Control Issue", "Paid Authority"),
    ("The Pet Collector", "No Ethics, Just Coins"),
    ("The Collar Capitalist", "Collar Capitalist"),
    ("Spends Coins To Feel Something", "Buyer of Obedience"),
    ("The Final Command", "Boss With a Leash"),
    ("Admin Approved Menace", "Black Leash Holder"),
    ("Gift From My Owner, Sadly", "Not My Choice"),
    ("Owner Picked This, Not Me", "Owner Wanted This"),
    ("Decorated Against My Will", "Against My Will"),
    ("This Was Not My Choice", "Trag Ich Leider"),
    ("My Owner Thinks This Is Funny", "Forced to Match"),
    ("Paid Humiliation Package", "Paid Humiliation"),
    ("Owner's Joke, My Problem", "Muss So Bleiben"),
    ("Ownerâ€™s Joke, My Problem", "Muss So Bleiben"),
    ("Petflix Hostage Label", "Branded by Bad Taste"),
    ("My Owner Needs A Hobby", "Wurde Nicht Gefragt"),
    ("Branded By Bad Taste", "Sorry, My Owner Paid"),
    ("Professional Disappointment", "Kein Refund"),
    ("Premium Embarrassment", "Walking Receipt"),
    ("Walking Receipt", "Würde Verkauft"),
    ("Wuerde Verkauft", "Würde Verkauft"),
    ("No Refund Available", "Public Mistake"),
    ("Public Shame Upgrade", "Scham Deluxe"),
    ("Personality Patch Failed", "Bad Purchase Energy"),
    ("Still Loading Dignity", "Quittung Auf Beinen"),
    ("Human Error In Pet Form", "Dignity Offline"),
    ("Proof Coins Were Misused", "Too Expensive For Pride"),
    ("Admin Should Have Stopped This", "Admin Should Have Stopped This"),
    ("Black Collar Asset", "Black Collar Asset"),
    ("Command Locked", "Command Locked"),
    ("Private Property Protocol", "Privatbesitz"),
    ("The Owner's Mark", "Owned in Public"),
    ("The Ownerâ€™s Mark", "Owned in Public"),
    ("Control Tagged", "Leash Protocol"),
    ("Collar Protocol Active", "Hart Gebrandet"),
    ("Bound And Branded", "Bound And Budgeted"),
    ("Claimed In Black", "Endstufe Besitz"),
    ("Obedience Pending", "Permanent Bad Decision"),
    ("Public Shame Upgrade Deluxe", "Deluxe Erniedrigt"),
]


BRAND_BUY_LINES = [
    '{user} kauft sich die Brandmarke "{brand}" für {price} Coins. Selbstachtung wäre günstiger gewesen, aber offenbar weniger sichtbar.',
    '{user} trägt jetzt "{brand}". Ob das hilft? Nein. Aber es sieht teuer aus.',
    '{user} hat {price} Coins für "{brand}" ausgegeben. Finanzielle Selbstkontrolle wurde offiziell beerdigt.',
    '"{brand}" gehört jetzt {user}. Die Gruppe wird gebeten, angemessen zu urteilen.',
    '{user} hat sich "{brand}" gekauft. Ein kleiner Schritt für den Bot, ein großer Rückschritt für die Würde.',
]


BRAND_SET_LINES = [
    '{user} trägt jetzt "{brand}". Tragisch, aber konsequent.',
    'Aktive Brandmarke geändert zu "{brand}". Die Außenwirkung bleibt fragwürdig.',
    '{user} präsentiert sich ab jetzt als "{brand}". Niemand hat gefragt, aber hier sind wir.',
]


BRAND_PET_LINES = [
    '{owner} kauft {pet} die Brandmarke "{brand}". {pet} wurde nicht gefragt. Das war vermutlich der Punkt.',
    '{pet} trägt jetzt "{brand}", bezahlt von {owner}. Freiwilligkeit wurde kurz geprüft und dann ignoriert.',
    '{owner} hat {pet} offiziell mit "{brand}" dekoriert. Geschmack bleibt weiterhin nicht strafbar, leider.',
    '{pet} wurde von {owner} mit "{brand}" markiert. Die Würde kann später gegen Coins zurückgekauft werden.',
    '{owner} hat {price} Coins bezahlt, damit {pet} jetzt "{brand}" tragen muss. Telegram war ein Fehler, aber wenigstens ein unterhaltsamer.',
]


BRAND_REMOVE_LINES = [
    '{pet} hat "{brand}" abgelegt und {price} Coins bezahlt. Würde zurückgekauft. Gebraucht, aber funktional.',
    '{pet} hat sich von "{brand}" freigekauft. Der Stolz war teuer, aber immerhin wieder da.',
    '{pet} zahlt {price} Coins, um "{brand}" loszuwerden. Der Owner wird gebeten, normal zu reagieren. Wird er nicht.',
    '"{brand}" wurde entfernt. {pet} hat damit bewiesen, dass Scham käuflich ist.',
    '{pet} kauft sich frei. Kurz dachte man, hier gäbe es Selbstbestimmung. Süß.',
]


VOLUNTARY_BRAND_TYPES = {"self", "owner", "shame", "legendary"}
FORCED_BRAND_TYPES = {"forced", "shame"}
